### ISSUE TITLE
undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE

### ISSUE THREAD

**Issue by Supernova1744** [atuleu/tf-convex-quad-iou#1]
After Installing [tf-convex-quad-iou](https://github.com/atuleu/tf-convex-quad-iou) and trying to run `tf_convex_quad_iou/tests/iou_matrix_test.py`

I got the following Error 

```
Traceback (most recent call last):
  File "tf_convex_quad_iou/tests/iou_matrix_test.py", line 3, in <module>
    from tf_convex_quad_iou import iou_matrix
  File "/home/user/.virtualenvs/tf-convex-quad-iou/lib/python3.8/site-packages/tf_convex_quad_iou/__init__.py", line 1, in <module>
    from tf_convex_quad_iou.iou_matrix_ops import iou_matrix
  File "/home/user/.virtualenvs/tf-convex-quad-iou/lib/python3.8/site-packages/tf_convex_quad_iou/iou_matrix_ops.py", line 12, in <module>
    iou_matrix_ops = load_library.load_op_library(
  File "/home/user/.virtualenvs/tf-convex-quad-iou/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/user/.virtualenvs/tf-convex-quad-iou/lib/python3.8/site-packages/tf_convex_quad_iou/custom_ops/iou/_iou_matrix_ops.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumE
```

**Comment by atuleu** [comment]
Did you install it from pip or from sources ?

I do not build manylinux wheel yet, so I will not support pip upload.

Which version of tensorflow do you use ? It may be some ABI problems.

**Comment by atuleu** [comment]
BTW the right way to run local test is through `bazelisk test`. The build process is quite involved.

I just tested, with tensorflow 2.8.0 (on which this small package was developed), the loading works fine.

It is not the case for tensorflow 2.9.1 which raise the same error. I do need to support 2.9.1 for one of my project, so I will fix this import error
